### ISSUE TITLE
MySQL wont start

### ISSUE THREAD

**Issue by atlet** [joeldg/bowhead#10]
I cloned your repo and run create_docker, but MySQL won't start.

**Comment by michelpa** [comment]
Same problem for me, it seems that it's because of log_slow_verbosity param...

**Comment by rxmg-joeldg** [comment]
This seems to be a windows issue, I will try it on a windows machine and see...

**Comment by sanmoh** [comment]
Same Issue with Ubuntu VM

 * Starting MySQL database server mysqld
   ...fail!
Starting redis-server: redis-server.
Adding user `www-data' to group `root' ...
Adding user www-data to group root
Done.
/etc/nginx/sites-enabled /var/www
/var/www
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Cloning into 'bowhead'...
Downloading/unpacking python-env
  Downloading python_env-1.0.0-py2-none-any.whl
Installing collected packages: python-env
Successfully installed python-env
Cleaning up...

**Comment by michelpa** [comment]
It seems that it's because the config file is for mariadb.

it works if you replace the installation of mysql-server by the mariadb server in docker file.

**Comment by sanmoh** [comment]
Thank you for that!

**Comment by Werninator** [comment]
@michelpa could you please tell me how to do that exactly?

**Comment by sanmoh** [comment]
Open the dockerfile located in docker/ and edit apt-get install -y mysql-server to apt-get install -y mariadb-server. 
Hope it helps 
Thanks to @michelpa

**Comment by h5gq3** [comment]
I changed to mariadb server but how can I connect to database on Sequel Pro? I'm running with Docker. When connecting to Sequel Pro it says:
Unable to connect via the socket, or the request timed out.

Double-check that the socket path is correct and that you have the necessary privileges, and that the server is running.

MySQL said: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
