### ISSUE TITLE
composer.update fails with 'ext-trader' issue even though trader is enabled

### ISSUE THREAD

**Issue by robertgdev** [joeldg/bowhead#109]
I'm trying to do a 'composer update' on a freshly pulled clone of your project. 

I have installed the trader extension using 

    pecl install trader

and my phpinfo shows the following info

    Trader Technical Analysis Library Support | enabled

Now, when I run 'composer update' I get the following error: 

    The requested PHP extension ext-trader * is missing from your system. Install or enable PHP's trader extension.

Any suggestions on how this could be resolved? 

FYI, I'm running PHP 7.1.15 on Ubuntu 17.10.

**Comment by ramzerof** [comment]
Hi rgasch, you must manually enable the extension
add in you php.ini:
extension=trader.so

**Comment by robertgdev** [comment]
As I'm saying above, my phpinfo() confirms that the trader extension is loaded/enabled. I'm on Linux so my setup is a bit different, but I've created an ini file for trader enabled it.

**Comment by ghost** [comment]
Are you running phpinfo though the CLI too ?

**Comment by ramzerof** [comment]
yes, you might have a specific php.ini for CLI
to test if the extension is on php CLI:
php -i | grep trader

to see which is the correct php.ini:
php -i | grep php.ini

**Comment by robertgdev** [comment]
You're 100% and I was an idiot on this issue. I had enabled the trader extension for apache but not for CLI. Sorry, my bad.
