### ISSUE TITLE
"Array" Error when making WC call in example_strategy

### ISSUE THREAD

**Issue by CognitiveDiscord** [joeldg/bowhead#43]
I've been killing myself trying to figure this out on my own, but it's just not happening for me.  I'm running the most recent version from Github in Docker on Ubuntu, and I get the following error when example_strategy tries to call Whaleclub when cci/cmo/mfi is -/+1.  Here's the output I get (same error with -vvv):

Signals for BTC/USD:cci:-1     cmo:0    mfi:-1    overbought underbought
Signals for BTC/USD:cci:-1     cmo:0    mfi:-1    overbought underbought
Signals for BTC/USD:cci:-1     cmo:-1   mfi:-1    overbought underboughtArray
(
    [error] => Array
        (
            [code] => 400
            [name] => Validation Error
            [message] => Market is missing or invalid.
        )

)

I suspect something is wrong in Util\Whaleclub.php, but I would assume that everyone else would be seeing this error if that was the case...  My WC demo key is valid, and example_usage returns my WC account info when I run it.  Any thoughts?

**Comment by robwil** [comment]
I ran into the same issue. The problem is that the order API call attempts to use "BTC/USD" as the market, but WC expects it to be "BTC-USD".

**Comment by CognitiveDiscord** [comment]
That seemed to fix it.  I made the following changes to app/Console/Commands/ExampleStrategyCommand.php:

	changed line 151 to:
                        , 'market' => 'BTC-USD'
	changed line 166 to:
                        , 'market' => 'BTC-USD'

Now I just have to deal with another API error (403, Minimum Size -> Minimum size at 20x leverage is 0.2 BTC), which should be simple enough now that I'm on the right track.  I'm still using the stock WC account, which gives you 5BTC to play with.  Thanks for the hint!
