### ISSUE TITLE
Bitfinex websocket error

### ISSUE THREAD

**Issue by vitoo** [joeldg/bowhead#55]
Hi,

looks like it can't connect to bitfinex, any idea ? Thanks

```
root@a4ac7326ad35:/var/www/bowhead# php artisan bowhead:websocket_bitfinex
BID error!
BID error!
ASK error!
ASK error!
ASK error!
ASK error!
ASK error!
BID error!
BID error!
BID error!
BID error!
BID error!

```

**Comment by pinguinman0** [comment]
it connects, it's just there aren't any display, if you log inside the BitfinexWebsocketCommand.php you can clearly see the messages

**Comment by rxmg-joeldg** [comment]
I think this is because bitfinex halted a lot of services,  I will look into it.

**Comment by lapham21** [comment]
Yeah I saw they are terminating US customer relations, I switched to using the coinbase websocket instead and it works instead as a work around.
