### ISSUE TITLE
OHLC.php some minutes not stored

### ISSUE THREAD

**Issue by tombrown86** [joeldg/bowhead#71]
I think there is a problem here.

Some minutes don't get logged

also it seems to be inserting data for prev min (in tick) as data for the current min.. is this intended?

**Comment by tombrown86** [comment]
UPDATE: I was seeing this issue in the 1m table for EUR_USD 

it's because it's referencing $bf_pair throughout the function, it should be using $instrument  

..so (in context of a forex pair) it was taking the last 1m entry time to be the last 1m entry time for BTC/USD :)


I will fork this + make a PR.. .eventually... I'll leave this open for the time being

**Comment by rxmg-joeldg** [comment]
This is all being redone now with new tables and models..
see https://github.com/joeldg/bowhead/commit/dff94eb858cc6c2ee5f75b9c1e8bab6e4156d733#diff-6be90f49f9c6d7fffa2550ba86608ce3

Reasoning is that we need to be able to track which exchange the data is coming in off.
Additionally, I will be adding in a data service for this separately..

I know that does not help you now, but soon this will not be used.

**Comment by tombrown86** [comment]
Good man...! can't wait to see the new stuff (and really can't wait for the ML work)

I just did a pull request anyway, in case you want the fix for the meantime

God speed
