### ISSUE TITLE
Call to undefined function Bowhead\Util\trader_ht_trendmode()

### ISSUE THREAD

**Issue by sutharkiran** [joeldg/bowhead#75]
Hello,

hey guys when i run this command "php artisan bowhead:test_trends" then i get below error
"  Call to undefined function Bowhead\Util\trader_ht_trendmode()  "

Error2:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-trader * is missing from your system. Install or enable PHP's trader extension.

how can i solve this error
Please Help  

Please help to fix this error
thanks advance

**Comment by vitoo** [comment]
You need to install trader extension

`pecl channel-update pecl.php.net && pecl install trader`
