### ISSUE TITLE
Timescale documentation seems to say the opposite (no need to strip indexes)

### ISSUE THREAD

**Issue by Driky** [joeldg/bowhead#92]
https://github.com/joeldg/bowhead/blob/cc20ccaa23ff251485ad842b8658bd1108a1565e/app/Http/Controllers/Controller.php#L49-L50

The [documentation](http://docs.timescale.com/v0.8/getting-started/migrating-data#same-db) under:
1. Creating the New Empty Table -> Convenient Method 

seems to show that we do not have to strip the indexes.

Am I missing something ?

PS: I do not now if you accept this kind of conversational issue but I haven't found a forum/discussion group dedicated to the project.

**Comment by rxmg-joeldg** [comment]
Hey, yea the timescale docs are kind of weird about it, but I tried a TON of ways to get the table to work and nothing but stripping out the indexes would go in.

**Comment by Driky** [comment]
oh ok my bad and good to know :)
